//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entidades.vialsur.prefectura
{
    using System;
    using System.Collections.Generic;

    public enum TipoUsuario
    {
        ADMINISTRADOR = 1,
        CHOFER = 2,
        MECANICO = 3,
        ADMINISTRATIVO = 4
    }

    public partial class emp_empleado
    {
        public int id { get; set; }
        public string cedula { get; set; }
        public Nullable<int> cargo_id { get; set; }
        public string pwd { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha_activacion { get; set; }
        public Nullable<System.DateTime> fecha_desactivacion { get; set; }
        public string per_persona_cedula_activacion { get; set; }
        public Nullable<int> tipo_usuario { get; set; }
        public string observaciones_activacion { get; set; }
        public string observaciones_desactivacion { get; set; }
    
        public virtual per_persona per_persona { get; set; }
    }
}
