//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entidades.vialsur.prefectura
{
    using System;
    using System.Collections.Generic;


    public enum TipoResponsable
    {
        CUSTODIO = 1,
        MECANICO = 2      
    }

    public partial class ve_vehiculo_responsable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ve_vehiculo_responsable()
        {
            this.orden = new HashSet<orden>();
        }
    
        public int id { get; set; }
        public string per_persona_cedula { get; set; }
        public Nullable<int> ve_vehiculo_id { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int tipo_responsable { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden> orden { get; set; }

        public virtual ve_vehiculo ve_vehiculo { get; set; }

    }
}
